---
version: 2
title: Create, read, check and delete pod with configMap volume
subtasks:
- title: Run a single workload with create/read/check/delete pod with configMap volume
  scenario:
    Kubernetes.create_and_delete_pod_with_configmap_volume:
      image: busybox
      command:
      - "sleep"
      - "3600"
      mount_path: /var/log/check.txt
      subpath: check.txt
      configmap_data:
        check.txt: |
          test
      check_cmd:
      - cat
      - /var/log/check.txt
      error_regexp: No such file
  runner:
    constant:
      concurrency: 2
      times: 10
  contexts:
    namespaces:
      count: 3
      with_serviceaccount: true
- title: Run create/read/check/delete pod with configMap volume with rps runner
  scenario:
    Kubernetes.create_and_delete_pod_with_configmap_volume:
      image: busybox
      command:
      - "sleep"
      - "3600"
      mount_path: /var/log/check.txt
      subpath: check.txt
      configmap_data:
        check.txt: |
          test
      check_cmd:
      - cat
      - /var/log/check.txt
      error_regexp: No such file
  runner:
    rps:
      rps: 2
      times: 10
  contexts:
    namespaces:
      count: 3
      with_serviceaccount: true
